SCREEN_WIDTH		= 2048
SCREEN_HEIGHT		= 1536

SCENE_BG_LAYER			= 0
SCENE_MAIN_LAYER		= 1
SCENE_TOUCH_LAYER		= 2
SCENE_UI_LAYER			= 3
SCENE_INTERFACE_LAYER	= 4
SCENE_LOADING_LAYER		= 5

SCENE_VISION		= 40

TEAM_FIRST_POS = 0
DISTANCE_BETWEEN_HEROES = 2
HERO_Z = 10
ANGLE_TP_X = 47.5

SCENE_STAR_MAX = 5

UI_TYPE_MAIN_MENU = 1;
UI_TYPE_SCENE_SELECT = 2;
UI_TYPE_SCENE_LOOT = 3;

LOADING_TYPE_INIT	= 0;
LOADING_TYPE_CCBI	= 1;
LOADING_TYPE_ANIM	= 2;
LOADING_TYPE_EVENT	= 3;
LOADING_TYPE_SCENE	= 4;
LOADING_TYPE_TILE	= 5;

SHOW_ENEMY_RECT = false;

--版本控制

VERSION_BUY_GAME = 1; --付费购买游戏版
VERSION_IAP_GAME = 2; --内付费购买金币版

PLATFORM_ANDROID = 1;
PLATFORM_APPLE = 2;




